package com.urlshortener.dto;

import lombok.Getter;

/**
 * DTO for handling URL information.
 * <p>
 * This class is used to encapsulate a URL, whether it is a long URL provided
 * for shortening or a short URL generated by the application.
 * </p>
 */
@Getter
public class UrlDto {

    private final String url;

    /**
     * Constructs a new {@code UrlDto} with the specified URL.
     *
     * @param url the URL to be encapsulated by this DTO.
     *
     */
    public UrlDto(String url) {
        this.url = url;
    }
}
